start_map: BRS_C069

maps:
  - name: BRS_C069
    north_angle: 1.5707963267948966
  - name: BRS_C025
    north_angle: 1.5707963267948966
  - name: Example
    north_angle: 1.5707963267948966

wormholes:
  - name: 2BRS_C025
    type: elevator_blast
    radius: 0.5
    locations:
      - map: BRS_C069
        position: [2.0, 0,4]
      - map: BRS C025
        position: [1.0, 1.0]

  - name: 2Example  
    type: elevator_blast
    radius: 0.5
    locations:
      - map: BRS_C025
        position: [1.0, 1,0]
      - map: Example
        position: [1.0, 1.0]

