start_map: dining-room

maps:
  - name: kitchen
    north_angle: 1.5707963267948966
  - name: shelf
    north_angle: 1.5707963267948966
  - name: dining-room
    north_angle: 1.5707963267948966

wormholes:
  - name: ForShelf
    type: normal
    radius: 0.5
    locations:
      - map: dining-room
        position: [1.0, 1.4]
      - map: shelf
        position: [1.0, 1.0]
  - name: dining-room
    type: normal
    radius: 0.5
    locations:
      - map: shelf
        position: [1.0, 1,0]
      - map: living-room
        position: [-2.0, -2.0]
