start_map: kitchen

maps:
  - name: kitchen
    north_angle: 1.5707963267948966
  - name: shelf
    north_angle: 1.5707963267948966
  - name: dining-room
    north_angle: 1.5707963267948966

wormholes:
  - name: 2BRS_C025
    type: elevator_blast
    radius: 0.5
    locations:
      - map: kitchen
        position: [1.0, 0.4]
        waiting_point: [1.0 0.4 3.132] # x, y, yaw
        floor: 0
        height: 2.0
      - map: shelf
        position: [1.0, 1.0]
        waiting_point: [4.687 16.517 3.135]
        floor: 1
        height: 2.0
  - name: 2Example
    type: elevator_blast
    radius: 0.5
    locations:
      - map: shelf
        position: [0.0, 0,0]
        waiting_point: [14.382 16.130 3.132] # x, y, yaw
        floor: 0
        height: 2.0
      - map: living-room
        position: [1.0, 1.0]
        waiting_point: [14.382 16.130 3.132] # x, y, yaw
        floor: 1
        height: 2.0
