start_map: shelf

maps:
  - name: kitchen
    north_angle: 1.5707963267948966
  - name: shelf
    north_angle: 1.5707963267948966
  - name: dining-room
    north_angle: 1.5707963267948966

wormholes:
  - name: kitchen
    radius: 0.5
    locations:
      - map: shelf
        position: [3.0, 1.4]
      - map: dining-room
        position: [1.0, 1.0]
  - name: dining-room
    radius: 0.5
    locations:
      - map: kitchen
        position: [1.0, 0.0]
      - map: shelf
        position: [0.0, 2.0]
  - name: shelf
    radius: 0.5
    locations:
      - map: kitchen
        position: [-1.0, -2.0]
      - map: dining-room
        position: [1.0, 2.0]
