start_map: living-room

maps:
  - name: living-room
    north_angle: 0.0
  - name: dining-room
    north_angle: 0.0

wormholes:
  - name: living-room
    type: custom
    radius: .5
    locations:
      - map: dining-room
        position: [1.47, -0.30]
      - map: kitchen
        position: [3.440246, 0.963580]
  - name: dining-room
    type: custom
    radius: .5
    locations:
      - map: living-room
        position: [-1.47, 0.30]
      - map: kitchen
        position: [-3.440246, -0.963580]
