start_map: livingC069

maps:
  - name: livingC069
    north_angle: 1.5707963267948966
  - name: diningC069
    north_angle: 1.5707963267948966

wormholes:
  - name: livingC069
    type: normal
    radius: 0.5
    locations:
      - map: diningC069
        position: [1.470428, 0.301883]
      - map: kitchenC069
        position: [3.440246, 0.963580]
  - name: diningC069
    type: normal
    radius: 0.5
    locations:
      - map: livingC069
        position: [1.480776, 0.334119]
