start_map: living-room-c069

maps:
  - name: living-room-c069
    north_angle: 1.5707963267948966
  - name: dining-room-c069
    north_angle: 1.5707963267948966

wormholes:
  - name: living-room-c069
    type: normal
    radius: 0.5
    locations:
      - map: dining-room-c069
        position: [1.470428, 0.301883]
      - map: kitchen-c069
        position: [3.440246, 0.963580]
  - name: dining-room-c069
    type: normal
    radius: 0.5
    locations:
      - map: living-room-c069
        position: [1.480776, 0.334119]
